---
- name: Check if ghostty PPA keyring exists
  become: true
  ansible.builtin.stat:
    path: /usr/share/keyrings/ghostty-ppa.gpg
  register: ghostty_keyring

- name: Download ghostty PPA signing key
  become: true
  vars:
    ghostty_ppa_key_id: "0x0721FDF5FECB88DC6920361657C8EF455CEAE491"
  ansible.builtin.get_url:
    url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search={{ ghostty_ppa_key_id }}"
    dest: /usr/share/keyrings/ghostty-ppa.asc
    mode: "0644"
  when: not ghostty_keyring.stat.exists

- name: Dearmor ghostty PPA signing key
  become: true
  ansible.builtin.command: gpg --dearmor -o /usr/share/keyrings/ghostty-ppa.gpg /usr/share/keyrings/ghostty-ppa.asc
  args:
    creates: /usr/share/keyrings/ghostty-ppa.gpg

- name: Add ghostty PPA repository
  become: true
  ansible.builtin.deb822_repository:
    name: ghostty-ppa
    types: deb
    uris: "https://ppa.launchpadcontent.net/mkasberg/ghostty-ubuntu/ubuntu"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    signed_by: /usr/share/keyrings/ghostty-ppa.gpg
    state: present
